### ISSUE TITLE
Multilanguage

### ISSUE THREAD

**Issue by LNDDYL** [ryuunoakaihitomi/rebootmenu#1]
請問作者打算加入多種語言嗎？

**Comment by ryuunoakaihitomi** [comment]
@LNDDYL 这样子的话，我可能还要再对文本润色一下，然后再出英文版的翻译了。这可能需要一段时间，因为我的空余时间并不多。感谢你对本项目的关注，顺便问一下，你是从哪里知道本项目的存在的。

**Comment by jonathanhzs** [comment]
做成类似凤凰os那样的，按钮是图标，背景全透明，看上去就是几个按钮的样子。

**Comment by ryuunoakaihitomi** [comment]
已记录。
