### ISSUE TITLE
搞成那种圆形按钮，背景透明，一个按钮一个功能。

### ISSUE THREAD

**Issue by jonathanhzs** [ryuunoakaihitomi/rebootmenu#26]
视屏幕方向，横排或者竖排，看起来就美观的多了。可以圆的，也可以稍微椭圆，为了按钮名称。

**Comment by ryuunoakaihitomi** [comment]
UI设计这部分实在是众口难调。除非日后严重影响了用户体验（比如阻碍了用户操作之类），不打算大幅度更改UI。
