### ISSUE TITLE
[BUG]添加通知栏下拉开关会导致其他开关间歇性失灵

### ISSUE THREAD

**Issue by AlisonAirline** [ryuunoakaihitomi/rebootmenu#32]
在通知栏下拉菜单中添加锁屏开关会导致surfboard的开关间歇性失灵且只发现此开关失灵。把本应用开关移除后恢复正常，开关和应用本身可以正常工作。

手机型号小米mix2s，安卓9

**Comment by ryuunoakaihitomi** [comment]
首先请根据模板进行bug反馈，如有再犯直接关闭。

然后请进行以下操作来帮助我查找此问题：
* 划掉所有后台卡片应用并重启手机
* 重复执行一次体现bug的操作
* [抓取错误报告](https://developer.android.google.cn/studio/debug/bug-report?hl=zh)并发送给我，如果是MIUI的话，拨号盘输入`*#*#284#*#*`

**Comment by AlisonAirline** [comment]
[提取码:3s34](https://pan.baidu.com/s/1DBy-e_OMtfLRdLEMDvh7NQ) 

抱歉，平时不怎么使用github。也没发现怎么传文件，只好传网盘了

**Comment by ryuunoakaihitomi** [comment]
非常抱歉。在排查日志的过程中，没有发现本应用和系统UI中相关部分的异常迹象，
且surfboard打印出的日志表示这个问题出现的原因很可能是surfboard的自发行为。
由于surfboard并不开源且apk加了混淆，请转而联系surfboard的开发者修复此问题。

**Comment by AlisonAirline** [comment]
好的，麻烦您了！
